### PR TITLE
Use the wget quiet flag and docker volumes instead of mkdir

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jsternberg** [comment]
@nathanielc @e-dard

**Comment by e-dard** [comment]
@jsternberg the `-q` is fine, but could you move the `VOLUME` up towards the `ENV` block? The last commands in a `Dockerfile` are usually the `ENTRYPOINT` and/or `CMD` ones.

**Comment by e-dard** [comment]
@jsternberg also, while you're there can you change the `CMD` `-config` path to `/var/lib/chronograf`? Will make the custom config file story simpler (which I'm adding to the `README`).

**Comment by e-dard** [comment]
@jsternberg Actually, scrap that last request. I see what's going on now re the config file. We should not specify a `-config` argument in the `CMD`, and then if the user wants to use a config they should explicitly specify the location.

**Pull request merged**
